# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
gems:                [jekyll-paginate]
permalink:           pretty
relative_permalinks: true

# Setup
title:               高悦凯的博客
tagline:             '后端为主，前端为辅'
description:         '走在编程的大路上……'
url:                 http://lanyon.getpoole.com
baseurl:             'http://gyk6985432.github.io/myBlog'
paginate:            5

# About/contact
author:
  name:              高悦凯
  twitter:           https://twitter.com/gyk6985432
  facebook:          https://www.facebook.com/profile.php?id=100009369283784
  email:             gyk6985432@gmail.com
  repo:

# Custom vars
template:            lanyon
